apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: docker.io/macpherson03/fastapi-sample:latest   # <— CHANGE to your image
        ports:
        - containerPort: 8080

