apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: slo-latency
  namespace: monitoring
spec:
  groups:
  - name: app-latency
    rules:
    - alert: HighP99Latency
      expr: |
        histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, handler)) > 0.5
      for: 10m
      labels:
        severity: page
      annotations:
        summary: "High p99 latency (>500ms) for {{ $labels.handler }}"
