apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
  - host: fastapi.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 80
