name: Build & Push BentoML (Iris) to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths:
      - "ml/bentoml/**"
      - ".github/workflows/bentoml-dockerhub.yml"
  workflow_dispatch:

env:
  REGISTRY: docker.io/${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: bento-iris

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps & BentoML
        working-directory: ml/bentoml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bentoml==1.3.19

      - name: Train model and save to Bento store
        working-directory: ml/bentoml
        run: python train.py

      - name: Build Bento
        working-directory: ml/bentoml
        run: bentoml build

      - name: Containerize Bento
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        working-directory: ml/bentoml
        run: |
          echo "Target image: $IMAGE"
          bentoml containerize service:latest -t "$IMAGE"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        run: docker push "$IMAGE"
